//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReference
    {
        public int ReferenceID { get; set; }
        public string NameSurname { get; set; }
        public string Mail { get; set; }
        public string ContactNumber { get; set; }
        public string Job { get; set; }
        public string ReferenceImage { get; set; }
    }
}
