//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casgem_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVideo
    {
        public int VideoID { get; set; }
        public string VideoTitle { get; set; }
        public string VideoContents { get; set; }
        public string VideoUrl { get; set; }
        public string VideoImageUrl { get; set; }
    }
}
